#!/usr/bin/env python3
# BloonsRandomizer.py

"""
Used to randomize towers in Bloons Tower Defense 6 (BTD6)
Intended to create challenge modes

Tower and hero rosters are loaded from data/towers.json,
which is regenerated from the wiki by tools/fetch_towers.py. Heroes are the
entries with category "Hero".
"""
import json
import os
import random
import tkinter as tk
from tkinter import ttk, messagebox

# global variables
waterBan = False
heroEnabled = True
mainUpgrades = 5
crossUpgrades = 2
numPrimary = 1
numMilitary = 1
numMagic = 1
numSupport = 1

# constants
defaultMessage = "Press Generate"
maxMonkeys = 5
# safety cap so an impossible config (e.g. no towers and no hero) can't loop forever
maxGenerationAttempts = 1000

# tower data (see data/towers.json, regenerated by tools/fetch_towers.py)
TOWER_DATA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "towers.json")


def loadTowerPools():
    """Loads towers.json and groups towers by category for random selection"""
    with open(TOWER_DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)
    pools = {category: [] for category in data["categories"]}
    for tower in data["towers"]:
        pools[tower["category"]].append(tower)
    return pools


towerPools = loadTowerPools()
towerByName = {tower["name"]: tower for pool in towerPools.values() for tower in pool}


class RandomizerApp:
    """The tkinter UI for the randomizer."""

    def __init__(self, root):
        self.root = root
        root.title("Bloons Randomizer")

        # tk-backed widget state
        self.primaryVar = tk.StringVar(value=str(numPrimary))
        self.militaryVar = tk.StringVar(value=str(numMilitary))
        self.magicVar = tk.StringVar(value=str(numMagic))
        self.supportVar = tk.StringVar(value=str(numSupport))
        self.waterBanVar = tk.BooleanVar(value=waterBan)
        self.heroVar = tk.BooleanVar(value=heroEnabled)

        # single screen: settings/controls on the left, the monkey list on the right
        main = ttk.Frame(root, padding=10)
        main.pack(fill="both", expand=True)
        main.columnconfigure(1, weight=1)
        main.rowconfigure(0, weight=1)

        self.build_controls(main)
        self.build_output(main)

    def build_controls(self, parent):
        """Builds the settings (top) and preset buttons (bottom) of the left column."""
        controls = ttk.Frame(parent)
        controls.grid(row=0, column=0, sticky="nsew", padx=(0, 10))

        # settings and Generate at the top
        settings = ttk.Frame(controls)
        settings.pack(side="top", fill="x")

        # per-category tower counts
        self._count_row(settings, 0, "Primary Towers", self.primaryVar)
        self._count_row(settings, 1, "Military Towers", self.militaryVar)
        self._count_row(settings, 2, "Magic Towers", self.magicVar)
        self._count_row(settings, 3, "Support Towers", self.supportVar)

        # water tower config
        ttk.Label(settings, text="Ban Water Towers").grid(row=4, column=0, sticky="w", pady=2)
        ttk.Checkbutton(settings, variable=self.waterBanVar).grid(row=4, column=1, sticky="w", pady=2)

        # hero config
        ttk.Label(settings, text="Enable Hero").grid(row=5, column=0, sticky="w", pady=2)
        ttk.Checkbutton(settings, variable=self.heroVar).grid(row=5, column=1, sticky="w", pady=2)

        ttk.Button(settings, text="Generate", command=self.on_generate).grid(
            row=6, column=0, columnspan=2, sticky="ew", pady=(10, 0))

        # quick presets pinned to the bottom of the window
        presets = ttk.Frame(controls)
        presets.pack(side="bottom", fill="x")
        # one of each tower type
        ttk.Button(presets, text="Default (One of Each)",
                   command=self.select_default).pack(fill="x", pady=1)
        # 4 of one tower type, 0 of the others
        for label, category in (("Primary Only", "Primary"),
                                ("Military Only", "Military"),
                                ("Magic Only", "Magic")):
            ttk.Button(presets, text=label,
                       command=lambda c=category: self.select_only(c)).pack(fill="x", pady=1)

    def _count_row(self, frame, row, label, var):
        """Adds a label + numeric entry row for a tower-count setting."""
        ttk.Label(frame, text=label, width=14).grid(row=row, column=0, sticky="w", pady=2)
        ttk.Entry(frame, textvariable=var, width=6).grid(row=row, column=1, sticky="w", pady=2)

    def build_output(self, parent):
        """Builds the monkey results list (right side)."""
        output = ttk.Frame(parent)
        output.grid(row=0, column=1, sticky="nsew")
        output.rowconfigure(1, weight=1)
        output.columnconfigure(0, weight=1)

        ttk.Label(output, text="Monkeys").grid(row=0, column=0, sticky="w")
        # a monospace font keeps the width in characters exact; 35 fits the
        # longest possible entry, e.g. "Monkey Buccaneer (2, 0, 5) [Camo]" (33).
        self.listbox = tk.Listbox(output, width=35, height=25, font="TkFixedFont")
        self.listbox.grid(row=1, column=0, sticky="nsew")
        self.listbox.insert(tk.END, defaultMessage)

    def read_settings(self):
        """Reads and validates the settings widgets into the module globals.

        Returns True on success, or False (after showing an error popup) if a
        tower count is not an integer in the range 0..maxMonkeys.
        """
        global waterBan, heroEnabled, numPrimary, numMilitary, numMagic, numSupport

        counts = {
            "Primary": self.primaryVar,
            "Military": self.militaryVar,
            "Magic": self.magicVar,
            "Support": self.supportVar,
        }
        parsed = {}
        for label, var in counts.items():
            value = parseTowerCount(var.get())
            if value == -1:
                messagebox.showerror(
                    "Error",
                    label + " Towers must be an integer from 0 to " + str(maxMonkeys))
                return False
            parsed[label] = value

        numPrimary = parsed["Primary"]
        numMilitary = parsed["Military"]
        numMagic = parsed["Magic"]
        numSupport = parsed["Support"]
        waterBan = self.waterBanVar.get()
        heroEnabled = self.heroVar.get()
        return True

    def select_default(self):
        """Preset: one of each tower type, then generate."""
        self.primaryVar.set("1")
        self.militaryVar.set("1")
        self.magicVar.set("1")
        self.supportVar.set("1")
        self.on_generate()

    def select_only(self, category):
        """Preset: set 4 of the given tower type and 0 of the others, then generate."""
        typeVars = {"Primary": self.primaryVar, "Military": self.militaryVar, "Magic": self.magicVar}
        self.primaryVar.set("0")
        self.militaryVar.set("0")
        self.magicVar.set("0")
        self.supportVar.set("0")
        typeVars[category].set("4")
        self.on_generate()

    def on_generate(self):
        """Validates settings then regenerates the monkey list."""
        if not self.read_settings():
            return
        self._set_list([str(tower) for tower in createList()])

    def _set_list(self, items):
        """Replaces the contents of the results listbox with the given items."""
        self.listbox.delete(0, tk.END)
        for item in items:
            self.listbox.insert(tk.END, item)


def parseTowerCount(userInput):
    """Takes the user inputted value from the number of monkeys inputs and ensures it is valid. Return -1 if invalid"""
    try:
        towerNum = int(userInput)
        if towerNum < 0 or towerNum > maxMonkeys:
            return -1
        return towerNum
    except ValueError:
        return -1


def hero():
    """Generates a random hero"""
    return genTowerFromCategory("Hero")


def primary():
    """Generates a random primary tower"""
    return genTowerFromCategory("Primary")


def military():
    """Generates a random military tower"""
    return genTowerFromCategory("Military")


def magic():
    """Generates a random magic tower"""
    return genTowerFromCategory("Magic")


def support():
    """Generates a random support tower"""
    return genTowerFromCategory("Support")


def genTowerFromCategory(category):
    """Selects a random tower (or hero) from the given category in the loaded data"""
    selected = random.choice(towerPools[category])
    if selected["isHero"]:
        # heroes level up instead of taking upgrade paths, so no path spread.
        # Only heroes that detect camo from level 1 count toward the guarantee.
        tower = Tower(selected["name"], selected["water"], None, isHero=True)
        tower.camo = selected["innateCamo"]
        return tower
    paths = genPaths()
    tower = Tower(selected["name"], selected["water"], paths)
    tower.camo = towerHasCamo(selected, paths)
    return tower


def towerHasCamo(towerData, paths):
    """Returns whether a tower with the given rolled paths detects camo bloons.

    A tower detects camo if it does so innately, or if any owned upgrade (the
    highest tier bought on a path) grants camo detection.
    """
    if towerData["innateCamo"]:
        return True
    for path in towerData["paths"]:
        ownedTier = paths[path["path"] - 1]
        if ownedTier >= 1 and path["tiers"][ownedTier - 1]["camo"]:
            return True
    return False


def pathsWithMain(main):
    """Builds a path spread with the given main (tier-5) path and a random cross path"""
    paths = [0, 0, 0]
    cross = random.randint(0, 2)
    while cross == main:
        cross = random.randint(0, 2)

    # these values determine the number of upgrades a tower can get on each path
    paths[main] = mainUpgrades
    paths[cross] = crossUpgrades
    return paths


def genPaths():
    """Generates the paths for a tower and returns an array of three integers that represent the towers"""
    return pathsWithMain(random.randint(0, 2))


def distinctMains(count):
    """Returns `count` main-path indices, kept distinct while possible.

    Only three paths exist, so once more than three copies are requested the
    extras necessarily reuse paths.
    """
    mains = []
    order = []
    while len(mains) < count:
        if not order:
            order = [0, 1, 2]
            random.shuffle(order)
        mains.append(order.pop())
    return mains


def enforceDistinctFifthTiers(monkeyList):
    """Reassigns main (tier-5) paths so duplicate towers don't share a fifth tier.

    Heroes are skipped (no paths). When a tower appears more times than there
    are paths, the excess copies reuse paths, which is unavoidable.
    """
    groups = {}
    for tower in monkeyList:
        if not tower.isHero:
            groups.setdefault(tower.name, []).append(tower)

    for name, group in groups.items():
        if len(group) < 2:
            continue
        for tower, main in zip(group, distinctMains(len(group))):
            tower.paths = pathsWithMain(main)
            tower.camo = towerHasCamo(towerByName[name], tower.paths)


def generateMonkeyList():
    """Creates the full list of usable monkeys for a player"""

    monkeyList = []

    # generate hero if enabled
    if heroEnabled:
        monkeyList.append(hero())

    # generate primary tower(s)
    for i in range(0, numPrimary):
        monkeyList.append(primary())

    # generate military tower(s)
    for i in range(0, numMilitary):
        monkeyList.append(military())

    # generate magic tower(s)
    for i in range(0, numMagic):
        monkeyList.append(magic())

    # generate support tower(s)
    for i in range(0, numSupport):
        monkeyList.append(support())

    enforceDistinctFifthTiers(monkeyList)
    return monkeyList


def checkConditions(towerList):
    """Checks a list of towers to make sure it meets the required conditions"""
    # Check for no water towers allowed
    if waterBan:
        for tower in towerList:
            if tower.water:
                return False
    # Camo detection guarantee: a non-empty set must include at least one
    # source that detects camo bloons
    if towerList and not any(tower.camo for tower in towerList):
        return False
    return True


def createList():
    """Generates a list of towers and verifies that it meets the required conditions"""
    monkeyList = generateMonkeyList()
    validList = checkConditions(monkeyList)
    attempts = 1
    while not validList and attempts < maxGenerationAttempts:
        monkeyList = generateMonkeyList()
        validList = checkConditions(monkeyList)
        attempts += 1
    return monkeyList


class Tower:
    """Contains all relevant data for a tower in-game.

    Heroes have no upgrade paths, so paths is None for them and only the name
    is shown; towers display their upgrade spread as "(top, middle, bottom)".
    """

    def __init__(self, name, water, paths, isHero=False):
        self.name = name
        self.water = water
        self.paths = paths
        self.isHero = isHero
        self.camo = False  # whether this rolled tower/hero detects camo bloons

    def __str__(self):
        if self.isHero:
            label = self.name
        else:
            label = self.name + " (" + str(self.paths[0]) + ", " + str(self.paths[1]) + ", " + str(self.paths[2]) + ")"
        if self.camo:
            label += " [Camo]"
        return label


def gen_UI():
    """Creates the UI upon launch"""
    root = tk.Tk()
    RandomizerApp(root)
    root.mainloop()


if __name__ == "__main__":
    gen_UI()
