#!/usr/bin/env python3
# BloonsRandomizer.py

"""
Used to randomize towers in Bloons Tower Defense 6 (BTD6)
Intended to create challenge modes

Tower rosters (Primary/Military/Magic/Support) and their water flags are loaded
from data/towers.json, which is regenerated from the wiki by
tools/fetch_towers.py. The hero list is maintained here (heroes are not towers).
"""
import json
import os
import random
import tkinter as tk
from tkinter import ttk, messagebox

# global variables
players = 1
waterBan = False
heroEnabled = True
mainUpgrades = 5
crossUpgrades = 2
numPrimary = 1
numMilitary = 1
numMagic = 1
numSupport = 1

# constants
defaultMessage = "Player Not Active"
maxMonkeys = 5

# tower data (see data/towers.json, regenerated by tools/fetch_towers.py)
TOWER_DATA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "towers.json")


def loadTowerPools():
    """Loads towers.json and groups towers by category for random selection"""
    with open(TOWER_DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)
    pools = {category: [] for category in data["categories"]}
    for tower in data["towers"]:
        pools[tower["category"]].append(tower)
    return pools


towerPools = loadTowerPools()


class RandomizerApp:
    """The tkinter UI for the randomizer."""

    def __init__(self, root):
        self.root = root
        root.title("Bloons Randomizer")

        # tk-backed widget state
        self.playersVar = tk.StringVar(value=str(players))
        self.primaryVar = tk.StringVar(value=str(numPrimary))
        self.militaryVar = tk.StringVar(value=str(numMilitary))
        self.magicVar = tk.StringVar(value=str(numMagic))
        self.supportVar = tk.StringVar(value=str(numSupport))
        self.waterBanVar = tk.BooleanVar(value=waterBan)
        self.heroVar = tk.BooleanVar(value=heroEnabled)

        notebook = ttk.Notebook(root)
        notebook.pack(fill="both", expand=True, padx=5, pady=5)

        notebook.add(self.build_settings_tab(notebook), text="Settings")
        notebook.add(self.build_results_tab(notebook), text="Monkey Results")

    def build_settings_tab(self, parent):
        """Builds the Settings tab where the run is configured."""
        frame = ttk.Frame(parent, padding=10)

        # number of players
        ttk.Label(frame, text="Number of Players").grid(row=0, column=0, sticky="w", pady=2)
        ttk.Combobox(frame, textvariable=self.playersVar, values=["1", "2", "3", "4"],
                     state="readonly", width=4).grid(row=0, column=1, sticky="w", pady=2)

        # per-category tower counts
        self._count_row(frame, 1, "Primary Towers", self.primaryVar)
        self._count_row(frame, 2, "Military Towers", self.militaryVar)
        self._count_row(frame, 3, "Magic Towers", self.magicVar)
        self._count_row(frame, 4, "Support Towers", self.supportVar)

        # water tower config
        ttk.Label(frame, text="Ban Water Towers").grid(row=5, column=0, sticky="w", pady=2)
        ttk.Checkbutton(frame, variable=self.waterBanVar).grid(row=5, column=1, sticky="w", pady=2)

        # hero config
        ttk.Label(frame, text="Enable Hero").grid(row=6, column=0, sticky="w", pady=2)
        ttk.Checkbutton(frame, variable=self.heroVar).grid(row=6, column=1, sticky="w", pady=2)

        return frame

    def _count_row(self, frame, row, label, var):
        """Adds a label + numeric entry row for a tower-count setting."""
        ttk.Label(frame, text=label, width=14).grid(row=row, column=0, sticky="w", pady=2)
        ttk.Entry(frame, textvariable=var, width=6).grid(row=row, column=1, sticky="w", pady=2)

    def build_results_tab(self, parent):
        """Builds the Monkey Results tab with the Generate button and per-player lists."""
        frame = ttk.Frame(parent, padding=10)

        ttk.Button(frame, text="Generate", command=self.on_generate).grid(
            row=0, column=0, columnspan=4, sticky="w", pady=(0, 5))

        # one listbox per possible player
        self.listboxes = []
        for i in range(4):
            column = ttk.Frame(frame)
            column.grid(row=1, column=i, padx=5, sticky="n")
            ttk.Label(column, text="Player " + str(i + 1)).pack(anchor="w")
            listbox = tk.Listbox(column, width=30, height=25)
            listbox.pack()
            listbox.insert(tk.END, defaultMessage)
            self.listboxes.append(listbox)

        return frame

    def read_settings(self):
        """Reads and validates the settings widgets into the module globals.

        Returns True on success, or False (after showing an error popup) if a
        tower count is not an integer in the range 0..maxMonkeys.
        """
        global players, waterBan, heroEnabled, numPrimary, numMilitary, numMagic, numSupport

        counts = {
            "Primary": self.primaryVar,
            "Military": self.militaryVar,
            "Magic": self.magicVar,
            "Support": self.supportVar,
        }
        parsed = {}
        for label, var in counts.items():
            value = parseTowerCount(var.get())
            if value == -1:
                messagebox.showerror(
                    "Error",
                    label + " Towers must be an integer from 0 to " + str(maxMonkeys))
                return False
            parsed[label] = value

        players = int(self.playersVar.get())
        numPrimary = parsed["Primary"]
        numMilitary = parsed["Military"]
        numMagic = parsed["Magic"]
        numSupport = parsed["Support"]
        waterBan = self.waterBanVar.get()
        heroEnabled = self.heroVar.get()
        return True

    def on_generate(self):
        """Validates settings then repopulates each player's tower list."""
        if not self.read_settings():
            return

        for i in range(int(players)):
            self._set_list(self.listboxes[i], [str(tower) for tower in createList()])

        # clear out the inactive players' listboxes
        for i in range(int(players), 4):
            self._set_list(self.listboxes[i], [defaultMessage])

    def _set_list(self, listbox, items):
        """Replaces the contents of a listbox with the given items."""
        listbox.delete(0, tk.END)
        for item in items:
            listbox.insert(tk.END, item)


def parseTowerCount(userInput):
    """Takes the user inputted value from the number of monkeys inputs and ensures it is valid. Return -1 if invalid"""
    try:
        towerNum = int(userInput)
        if towerNum < 0 or towerNum > maxMonkeys:
            return -1
        return towerNum
    except ValueError:
        return -1


def hero():
    """Generates a random hero"""

    heroes = ["Quincy", "Gwendolin", "Striker Jones", "Obyn Greenfoot", "Geraldo", "Captain Churchill", "Benjamin", "Ezili",
              "Pat Fusty", "Adora", "Admiral Brickell", "Etienne", "Sauda", "Psi", "Corvus", "Rosalia"]

    waterHeroes = ["Admiral Brickell"]

    return genTower(heroes, waterHeroes)


def primary():
    """Generates a random primary tower"""
    return genTowerFromCategory("Primary")


def military():
    """Generates a random military tower"""
    return genTowerFromCategory("Military")


def magic():
    """Generates a random magic tower"""
    return genTowerFromCategory("Magic")


def support():
    """Generates a random support tower"""
    return genTowerFromCategory("Support")


def genTowerFromCategory(category):
    """Selects a random tower from the given category in the loaded tower data"""
    selected = random.choice(towerPools[category])
    return Tower(selected["name"], selected["water"], genPaths())


def genTower(towers, waterTowers):
    """Generates a random tower/hero from the given name list and its water-based subset.

    Used for the hardcoded hero list; towers are drawn from data via genTowerFromCategory.
    """

    randInt = random.randint(0, (len(towers) - 1))
    water = False

    selectedTower = towers[randInt]

    #water towers
    if selectedTower in waterTowers:
        water = True

    return Tower(selectedTower, water, genPaths())


def genPaths():
    """Generates the paths for a tower and returns an array of three integers that represent the towers"""
    paths = [0, 0, 0]
    main = random.randint(0, 2)
    cross = random.randint(0, 2)
    while cross == main:
        cross = random.randint(0, 2)

    # assigns these global variables that determine the number of upgrades a tower can get
    paths[main] = mainUpgrades
    paths[cross] = crossUpgrades
    return paths


def generateMonkeyList():
    """Creates the full list of usable monkeys for a player"""

    monkeyList = []

    # generate hero if enabled
    if heroEnabled:
        monkeyList.append(hero())

    # generate primary tower(s)
    for i in range(0, numPrimary):
        monkeyList.append(primary())

    # generate military tower(s)
    for i in range(0, numMilitary):
        monkeyList.append(military())

    # generate magic tower(s)
    for i in range(0, numMagic):
        monkeyList.append(magic())

    # generate support tower(s)
    for i in range(0, numSupport):
        monkeyList.append(support())

    return monkeyList


def checkConditions(towerList):
    """Checks a list of towers to make sure it meets the required conditions"""
    # Check for no water towers allowed
    if waterBan:
        for tower in towerList:
            if tower.water:
                return False
    return True


def createList():
    """Generates a list of towers and verifies that it meets the required conditions"""
    monkeyList = generateMonkeyList()
    validList = checkConditions(monkeyList)
    while not validList:
        monkeyList = generateMonkeyList()
        validList = checkConditions(monkeyList)
    return monkeyList


class Tower:
    """Contains all relevant data for a tower in-game"""

    def __init__(self, name, water, paths):
        self.name = name
        self.water = water
        self.paths = paths

    def __str__(self):
        return str(self.name + " (" + str(self.paths[0]) + ", " + str(self.paths[1]) + ", " + str(self.paths[2]) + ")")


def gen_UI():
    """Creates the UI upon launch"""
    root = tk.Tk()
    RandomizerApp(root)
    root.mainloop()


if __name__ == "__main__":
    gen_UI()
